// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0xOPfOWlg11HKelrh7KmZcYcKoYN0Fqo',
    appId: '1:634220539093:web:78cb575f3bb1988968c65c',
    messagingSenderId: '634220539093',
    projectId: 'chat-f7fef',
    authDomain: 'chat-f7fef.firebaseapp.com',
    storageBucket: 'chat-f7fef.appspot.com',
    measurementId: 'G-35V70BG0XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB3IxD_IkEj5L3KQzdWYQXQIQyVGx5-zQ',
    appId: '1:634220539093:android:ed11eaef3f0238d968c65c',
    messagingSenderId: '634220539093',
    projectId: 'chat-f7fef',
    storageBucket: 'chat-f7fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsJJxfTKOPHIjjcScy7apJTZMgKWMMbB0',
    appId: '1:634220539093:ios:6f987acf85b1bd7868c65c',
    messagingSenderId: '634220539093',
    projectId: 'chat-f7fef',
    storageBucket: 'chat-f7fef.appspot.com',
    iosClientId: '634220539093-5egq6to3ot5jv0e01gb7aves515nkhg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.techMedia',
  );
}
